# Site settings
title: TEDxTufts
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.tedxtufts.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# exclusions:
exclude:
 - Gruntfile.js
 - bower_components
 - node_modules
 - aws-s3-config.json
 - scss
 - config.rb
 - package.json
